import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { Infer, v } from "convex/values";

// default user roles. can add / remove based on the project as needed
export const ROLES = {
  ADMIN: "admin",
  USER: "user",
  MEMBER: "member",
} as const;

export const roleValidator = v.union(
  v.literal(ROLES.ADMIN),
  v.literal(ROLES.USER),
  v.literal(ROLES.MEMBER),
);
export type Role = Infer<typeof roleValidator>;

const schema = defineSchema(
  {
    // default auth tables using convex auth.
    ...authTables, // do not remove or modify

    // the users table is the default users table that is brought in by the authTables
    users: defineTable({
      name: v.optional(v.string()), // name of the user. do not remove
      image: v.optional(v.string()), // image of the user. do not remove
      email: v.optional(v.string()), // email of the user. do not remove
      emailVerificationTime: v.optional(v.number()), // email verification time. do not remove
      isAnonymous: v.optional(v.boolean()), // is the user anonymous. do not remove

      role: v.optional(roleValidator), // role of the user. do not remove

      // Lovable-replica user preferences
      themeChoice: v.optional(v.union(v.literal("light"), v.literal("dark"))),
      onboardingComplete: v.optional(v.boolean()),
    }).index("email", ["email"]), // index for the email. do not remove or modify

    // A "project" is a chat thread in the Lovable replica
    projects: defineTable({
      userId: v.id("users"),
      name: v.string(),
      isArchived: v.optional(v.boolean()),
      // True while the scheduled AI action is generating the assistant reply.
      replyPending: v.optional(v.boolean()),

      // E2B sandbox state for the generated app (fragments-style builder).
      sandboxId: v.optional(v.string()), // e2b sandbox id, lets us reconnect later
      previewUrl: v.optional(v.string()), // https://<id>-<port>.e2b.app live preview
      sandboxStatus: v.optional(
        v.union(
          v.literal("idle"),
          v.literal("building"),
          v.literal("running"),
          v.literal("error"),
        ),
      ),
    }).index("by_user", ["userId"]),

    // Messages inside a project thread
    messages: defineTable({
      projectId: v.id("projects"),
      userId: v.id("users"),
      role: v.union(v.literal("user"), v.literal("assistant")),
      content: v.string(),
      thoughtSeconds: v.optional(v.number()),
      // Optional metadata about a code-generation turn.
      filePath: v.optional(v.string()),
      fileCount: v.optional(v.number()),
      sandboxCreated: v.optional(v.boolean()),
    }).index("by_project", ["projectId"]),

    // Source files generated by the AI for a project (mirrored from the sandbox).
    generatedFiles: defineTable({
      projectId: v.id("projects"),
      userId: v.id("users"),
      path: v.string(), // relative path, e.g. src/App.jsx
      content: v.string(),
    }).index("by_project_path", ["projectId", "path"]),
  },
  {
    schemaValidation: false,
  },
);

export default schema;
